### PR TITLE
Add Colab TPU initialization

### PR DESCRIPTION
**Pull request by ayush-1506**
Using TPUs with JAX on colab requires an extra step. I ran it for a couple of examples with TPU acceleration on colab and it seems to work.

### CODE REVIEW

**Comment by ayush-1506** [comment]
Coincidentally, also fixes #202

**Comment by ayush-1506** [comment]
Also fixes #202 .

**Comment by ayush-1506** [comment]
Without TPU, it's going to throw a KeyError (`COLAB_ADDR_TPU not found`).

**Comment by ayush-1506** [comment]
@fabianp How about just catching this error and logging something like `TPU not detected, running without it` if TPU isn't detected?

**Comment by fabianp** [comment]
yes! that's a good idea. Could you please modify the code to do this? Thanks!

**Comment by ayush-1506** [comment]
@fabianp should work now.

**Comment by fabianp** [comment]
excellent! We’re almost there. A couple of things to do before merging:

0. pull from the main repository. I think there’s a new notebook in the folder notebooks/perturbed_optimizers . Please add the same trick to allow it to run on TPUs.
1. sync the markdown jupyter notebooks as mentioned here: https://jaxopt.github.io/stable/developer.html#syncing-notebooks
2. squash all the commits in this pull request so this pull request contains a single commit.

Thanks again for the contribution!

**Comment by fabianp** [comment]
thanks @ayush-1506 . One last thing. Please add a a comment before the `import jax.tools.colab_tpu` line to explain what is happening? something like `# activate TPUs if available`. After that we're good to merge

**Review by fabianp — APPROVED** [review]

**Comment by fabianp** [comment]
all done and merged. Thanks @ayush-1506 !

**Pull request merged**
