### PR TITLE
robust training notebook

### PR DESCRIPTION
**Pull request by fabianp**

### CODE REVIEW

**Review by mblondel — APPROVED** [review]
Thanks a lot!

**Comment by fabianp** [comment]
This is now ready for review :-)

Once it's accepted I'll create another PR deleting the python examples that have been migrated to notebooks.

Current view of the notebook gallery:

image

I also added an image to the notebook to show an (original, adversarial image) pair with its prediction:

image

**Comment by fabianp** [comment]
Update: I've now renamed the example from robust training to adversarial training,  I think this is more accurate and standard

(let me know what you think @GeoffNN )

**Comment by GeoffNN** [comment]
Agreed that it's more standard! The example is cool 😃

**Pull request merged**
