### PR TITLE
Fixes EqualityConstrainedQP when not using iterative refinement.

### PR DESCRIPTION
**Pull request by GeoffNN**
Co-authored-by: Aditi Krishnapriyan <a1k12@users.noreply.github.com>

### CODE REVIEW

**Comment by GeoffNN** [comment]
Aditi signed the CLA since the bot was run.

**Comment by mblondel** [comment]
Thanks! Ideally, I would add a non-regression test (a unit test that failed before this change and succeeds thanks to this change).

**Comment by GeoffNN** [comment]
Got it, I can add that!

**Comment by GeoffNN** [comment]
Moved to #127 for squashing etc

**Pull request closed without merging**
