### PR TITLE
enable `pip` caching in CI + add `pyproject.toml`

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Changes made by this PR can be summarized as follows:

- Use an updated version of `actions/setup-python` so as to allow the caching of `pip`.

### CODE REVIEW

**Comment by SauravMaheshkar** [comment]
@mblondel Request for Review

**Comment by SauravMaheshkar** [comment]
I merged with main in [0b7ab26](https://github.com/google/jaxopt/pull/379/commits/0b7ab26eeaa016cb34c5501afc725bb484fee20f), maybe that helps.

**Comment by SauravMaheshkar** [comment]
These errors are independent of the changes made by this PR, only the `actions/setup-python` step of the workflow is affected by this PR.

Also now that we are trying to cache the dependencies, we should remove the "Install dependencies" step.

**Comment by mblondel** [comment]
The failures were because this [revert](https://github.com/google/jax/pull/14262) was not in the latest JAX release yet. Now it is and we're back to green.

**Comment by SauravMaheshkar** [comment]
Because of [af3d4a2](https://github.com/google/jaxopt/pull/379/commits/af3d4a2e44750cfb58002d0893b96e5450fcacd2), instead of a separate `pylintrc` and `setup.py`, we now would have all the configurations within the `pyproject.toml` file leading to a overall minimal code structure. I recently proposed similar changes to geoopt and flax.

@mblondel thoughts on this ?

**Comment by SauravMaheshkar** [comment]
@mblondel Request for Review

**Comment by SauravMaheshkar** [comment]
@mblondel sorry for that, I had to change the build-backend to `setuptools`. This should pass now 🤞🏽

**Comment by SauravMaheshkar** [comment]
@mblondel @yashk2810 Request for Review

**Comment by SauravMaheshkar** [comment]
Shifted to #411

**Pull request closed without merging**
