### PR TITLE
Fixes a shape bug in the previous code for the robust example

### PR DESCRIPTION
**Pull request by GeoffNN**

### CODE REVIEW

**Review by fabianp — APPROVED** [review]

**Comment by mblondel** [comment]
Could you squash commits? Thanks!

**Comment by GeoffNN** [comment]
Done!

**Comment by GeoffNN** [comment]
Also fixed a variable msinamed in the `shuffle` function.

**Comment by mblondel** [comment]
Thanks! (and good catch regarding `ds`!)

**Pull request merged**
