### PR TITLE
Add callback mechanism to ScipyMinimize

### PR DESCRIPTION
**Pull request by fabianp**
This is an option that exists in scipy.optimize.minimize, but which we failed to expose, and its essential for detailed benchmarks

### CODE REVIEW

**Comment by fabianp** [comment]
wait, I forgot to add the docstring for this option!

**Comment by fabianp** [comment]
hmmm, one thing that I had underestimated is the flattening / unflattening of pytrees. A flattened numpy array is what gets passed to the callback function, even when the input to ScipyMinimize is a pytree. 

Should we be doing the work on unflattening the numpy array so that the user codes the callback expecting a pytree? This seems the most reasonable to me. What do you think @mblondel ?

**Comment by mblondel** [comment]
I agree a pytree would be more natural.

**Comment by fabianp** [comment]
I documented the callback option in the docstring and added the unraveling for the callback (and a test for it). I think this is now ready for review

**Comment by mblondel** [comment]
Thanks @fabianp! 

@fllinares can you take a look when you get some time? Thanks

**Review by fllinares — APPROVED** [review]
Thanks a lot Fabian, LGTM!!

**Pull request merged**
