### PR TITLE
Fix print for verbose=False

### PR DESCRIPTION
**Pull request by vroulet**
Fix https://github.com/google/jaxopt/issues/571, added tests.

### CODE REVIEW

**Comment by Joshuaalbert** [comment]
I noticed a difference between linesearch verbosity setting for LBFGS and NonlinearCG.

In LBFGS
```python
self.linesearch_solver = _setup_linesearch(
        linesearch=self.linesearch,
        fun=_fun_with_aux,
        value_and_grad=self._value_and_grad_with_aux,
        has_aux=True,
        maxlsiter=self.maxls,
        max_stepsize=self.max_stepsize,
        jit=self.jit,
        unroll=unroll,
        verbose=self.verbose,
    )
```

In NonlinearCG:
```python
linesearch_solver = _setup_linesearch(
        linesearch=self.linesearch,
        fun=_fun_with_aux,
        value_and_grad=self._value_and_grad_with_aux,
        has_aux=True,
        maxlsiter=self.maxls,
        max_stepsize=self.max_stepsize,
        jit=self.jit,
        unroll=unroll,
        verbose=int(self.verbose)-1
    )
```

Maybe multi-level verbosity is actually not so useful?

**Comment by vroulet** [comment]
Yes, I had forgotten the multiple level verbosity for lbfgs. It's been corrected in this PR.

**Review by fabianp — APPROVED** [review]
looks good to me, thanks!

**Comment by rupeshknn** [comment]
I still face this issue, probably because there has been no release since Jan 10. when is the next release being planned?

**Pull request merged**
