### PR TITLE
Added Broyden in common tests + took into account LS fail

### PR DESCRIPTION
**Pull request by zaccharieramzi**
EDIT: will not try to use the new LS API for lack of time, will do so another day

### CODE REVIEW

**Comment by zaccharieramzi** [comment]
@fabianp ready for review

**Comment by fabianp** [comment]
LGTM except for test failures :-)

**Comment by mblondel** [comment]
Thanks! Can you squash commits? Then I'll merge

**Comment by zaccharieramzi** [comment]
I had a weird history issue I could not get rid of, so I am closing this in favor of #471, sorry for the inconvenience...

**Pull request closed without merging**
