### PR TITLE
enable `pip` caching in CI + add `pyproject.toml`

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Port over changes from #379.

Changes made by this PR can be summarized as follows:

- Use an updated version of `actions/setup-python` so as to allow the caching of `pip`.
- switch to `pyproject.toml` as a build backend.

### CODE REVIEW

**Comment by SauravMaheshkar** [comment]
@mblondel Request for Review

**Comment by SauravMaheshkar** [comment]
It seems like the build is passing, but the tests are failing. I don't think the tests are related to the changes proposed by this PR. Infact the step changed by this PR ("Build") works.

**Comment by mblondel** [comment]
The CI failures should be fixed when #412 is merged.

I'm am not familiar with poetry. What would be the benefits? I see that you removed our setup.py file. This will break our [workflow](https://github.com/google/jaxopt/blob/main/.github/workflows/publish_to_pypi.yml).

I'm +1 for the caching but less convinced for poertry. It would be great if you could submit the caching as a separate PR.

**Comment by SauravMaheshkar** [comment]
I'm not proposing we switch to using poetry. We'll still use pip as the package manager, it's just that the metadata will be specified in the `pyproject.toml` file. And I've updated the workflow as well so that shouldn't break.

**Pull request closed without merging**
